CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL CHECK (role IN ('FAMILY', 'CENTER', 'ADMIN'))
);

CREATE TABLE family_waste (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_name VARCHAR(255) NOT NULL,
    waste_type VARCHAR(255) NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status IN ('PENDING', 'PROCESSING', 'RECYCLED')),
    created_at BIGINT
);

CREATE INDEX idx_family_waste_family_name ON family_waste (family_name);
CREATE INDEX idx_family_waste_status ON family_waste (status);